### PR TITLE
Bump pygmt from 0.6.1 to 0.7.0, geopandas from 0.10.2 to 0.11.0

### PR DESCRIPTION
**Pull request by weiji14**
Supersedes #35. Part of https://github.com/GenericMappingTools/pygmt/issues/1966

### CODE REVIEW

**Review by seisman — APPROVED** [review]

**Comment by weiji14** [comment]
The Julia build seems to be broken, need to fix it in a separate PR so that the try-gmt mybinder works.

```
Failed to precompile GMT [5752ebe1-31b9-557e-87aa-f909b540aa54] to /srv/julia/pkg/compiled/v1.7/GMT/jl_OC8oeb.
ERROR: LoadError: could not load library "/srv/conda/envs/notebook/lib/libgmt.so"
/srv/julia/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /srv/conda/envs/notebook/lib/./libgdal.so.31)
```

**Comment by maxrjones** [comment]
the failure was explained here - https://github.com/GenericMappingTools/try-gmt/pull/36#issuecomment-1160597300, which suggests there's nothing we could do other than temporarily disable the julia component.

**Comment by weiji14** [comment]
> the failure was explained here - https://github.com/GenericMappingTools/try-gmt/pull/36#issuecomment-1160597300, which suggests there's nothing we could do other than temporarily disable the julia component.

Ah ok, then let's temporarily disable Julia. Or we can find a way to separate GMT C/Julia/Python into different mybinder environments.

**Comment by joa-quim** [comment]
On a long term there is something I'd like to do: To build GMT for the three main OS's using VcPkg. This would create installers for the 3 (plus BSD?) of them. I've looked at the GH actions but can't understand where and how we can check that the MSVC compiler is installed.

**Comment by PaulWessel** [comment]
I got an update today for clang and C library (for macports):
`--->  Activating clang-11 @11.1.0_6+analyzer+emulated_tls+libstdcxx`
Perhaps this is in response to the above cluster*k and that relief is on the way?

**Pull request merged**
