### PR TITLE
Bump GMT to 6.4.0

### PR DESCRIPTION
**Pull request by meghanrjones**

### CODE REVIEW

**Comment by seisman** [comment]
Also need to update the GMT version information in README.

**Review by PaulWessel — APPROVED** [review]

**Comment by meghanrjones** [comment]
Not sure if I should ignore the validator failure for the Julia components

**Comment by PaulWessel** [comment]
> Not sure if I should ignore the validator failure for the Julia components

Not sure what that means - probably @joa-quim territory?

**Comment by joa-quim** [comment]
Not our fault and really nothing we (I) can do for now. 
The problem is that Unix once again played its favorite game: **breaking** dependencies.

On *nix, when no GMT if found, GMT.jl automatically installs one via Conda. But Conda decided to start use the shiny shiny new GCC12 that has a new ``libstdc++`` incompatible with predecessors. So those GMT builds cannot be used with current Julia(s) because of that. dd to it that they (the master Julians) have not been able to [cross compile libraries from GCC 12](https://github.com/JuliaLang/julia/pull/45582).

See what Windows users are safe from because we use **obvious** MSVC framework to build our binaries?


```
Failed to precompile GMT [5752ebe1-31b9-557e-87aa-f909b540aa54] to /srv/julia/pkg/compiled/v1.7/GMT/jl_gIdOKB.
ERROR: LoadError: could not load library "/srv/conda/envs/notebook/lib/libgmt.so"
/srv/julia/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /srv/conda/envs/notebook/lib/./libgdal.so.31)
```

**Pull request merged**
